### ISSUE TITLE
"system.nullreferenceexception" error

### ISSUE THREAD

**Issue by sush1man** [EugeneSunrise/reWASD#102]
I may be too dumb to overlook such an easy error, but I request adittional help on this matter.

I followed all of the insructions on both video tutorials and yet I still stumble upon this error. Any ideas?
![image](https://github.com/EugeneSunrise/reWASD/assets/157137312/4b4fdc99-00df-4f3e-a7bc-9260ebd44856)

Thank you!

**Comment by TonyHacker03** [comment]
same
