### ISSUE TITLE
gamemapdriver.sys

### ISSUE THREAD

**Issue by eyehack84** [EugeneSunrise/reWASD#107]
Im looking for a file in the system 32 folder related to Rewasd; something named gamemapdriver.sys? Do you have any idea on a possible system file that responds to emulation of controllers. Thank you in advance! I tried getting this info from a Rewasd dev but they couldn't think of the location

**Comment by EugeneSunrise** [comment]
> Im looking for a file in the system 32 folder related to Rewasd; something named gamemapdriver.sys? Do you have any idea on a possible system file that responds to emulation of controllers. Thank you in advance! I tried getting this info from a Rewasd dev but they couldn't think of the location

You can look into rewasd installer via dnSpy, where and how the drivers are installed

**Comment by eyehack84** [comment]
Thank you so much!
