### ISSUE TITLE
Сonfig application issue

### ISSUE THREAD

**Issue by DeL240** [EugeneSunrise/reWASD#113]
Activision recently blocked reWASD, but there is a way out - 2 pc. When I wanted to connect my 2 pc I found a problem, my config is not applied. And it doesn't work on both computers. Maybe I don't understand something and this version is not supposed to be used.
![Аннотация 2024-01-23 044850](https://github.com/EugeneSunrise/reWASD/assets/157428136/0022513c-2970-4d35-946a-4ec664af1a50)

**Comment by EugeneSunrise** [comment]
Watch guides, check readme, check closed issues, check open/closed discussions, dont close dnspy while debugging etc. Good luck
