### ISSUE TITLE
Bypass for COD Warzone 

### ISSUE THREAD

**Issue by boggossdz13** [EugeneSunrise/reWASD#115]
Heyn thanks for your work, it ll be good If we find a way to bypass cod warzone new update for rewasd

**Comment by EugeneSunrise** [comment]
> Heyn thanks for your work, it ll be good If we find a way to bypass cod warzone new update for rewasd 

Hello, you can check open discussions, in short, I won’t be able to make a bypass cuz I don’t have a PC on the x86 platform and don’t play games
