### ISSUE TITLE
blinking / unresponsive apply to slot button 

### ISSUE THREAD

**Issue by godh2** [EugeneSunrise/reWASD#12]
i make / open a config and the apply to slot button is unresponsive ive reinstalled it and installed it i did everything and uninstalled the uncrack version of rewasd but its still unresponsive

**Comment by Crazyhead90** [comment]
Same, I think it is due to not installing the gamepad driver? Normally it does that on first launch, but without a key it instantly goes to "not activated" and skip the installation part.

**Comment by godh2** [comment]
yeah im pretty sure they patched this crack or somthing

**Comment by godh2** [comment]
i might just buy the real 1 ;/

**Comment by EugeneSunrise** [comment]
Guys, just chill and wait fix

**Comment by godh2** [comment]
ok sorry to sound annoying but do u know when its going to be out?? the next fix

**Comment by EugeneSunrise** [comment]
> ok sorry to sound annoying but do u know when its going to be out?? the next fix

I'll try to release a working build tomorrow/later tomorrow

**Comment by albirizo** [comment]
> > ok sorry to sound annoying but do u know when its going to be out?? the next fix
> 
> I'll try to release a working build tomorrow/later tomorrow

any updates on the release? is it coming soon or delayed?

**Comment by EugeneSunrise** [comment]
> > > ok sorry to sound annoying but do u know when its going to be out?? the next fix
> 
> > 
> 
> > I'll try to release a working build tomorrow/later tomorrow
> 
> 
> 
> any updates on the release? is it coming soon or delayed?

Updated readme, check

**Comment by EugeneSunrise** [comment]
CHECK README AND GIVE ME FEEDBACK

**Comment by albirizo** [comment]
> CHECK README AND GIVE ME FEEDBACK

personally I don't see the need for a 7.0 crack, so I would be more than happy to have a 6.6 crack.

please release a guide. thank you!

**Comment by EugeneSunrise** [comment]
> > CHECK README AND GIVE ME FEEDBACK
> 
> 
> 
> personally I don't see the need for a 7.0 crack, so I would be more than happy to have a 6.6 crack.
> 
> 
> 
> please release a guide. thank you!

Ok

**Comment by albirizo** [comment]
> > > CHECK README AND GIVE ME FEEDBACK
> > 
> > 
> > personally I don't see the need for a 7.0 crack, so I would be more than happy to have a 6.6 crack.
> > please release a guide. thank you!
> 
> Ok

Not to be annoying, but when are you planning on releasing this guide/release?

**Comment by EugeneSunrise** [comment]
> > > > CHECK README AND GIVE ME FEEDBACK
> 
> > > 
> 
> > > 
> 
> > > personally I don't see the need for a 7.0 crack, so I would be more than happy to have a 6.6 crack.
> 
> > > please release a guide. thank you!
> 
> > 
> 
> > Ok
> 
> 
> 
> Not to be annoying, but when are you planning on releasing this guide/release?

This hour bro

**Comment by godh2** [comment]
im gunna buy the real rewasd bruh

**Comment by EugeneSunrise** [comment]
> im gunna buy the real rewasd bruh
> 
> 

Good, this actually good software

**Comment by godh2** [comment]
i bought it and the fucking thing went and it says it takes 3 fucking days to process the payment wtf

**Comment by EugeneSunrise** [comment]
Check releases and give me feedback

**Comment by EugeneSunrise** [comment]
6.6 ver ready, 7.0 will be later, any questions? Create NEW issue
