### ISSUE TITLE
REWASD Version 6.7?

### ISSUE THREAD

**Issue by titeta231** [EugeneSunrise/reWASD#13]
So, I saw that they're making a crack for the version 6.6 and I want to ask the owner if it's possible to make a crack for the version 6.7 since it has the Steam Deck Support.

**Comment by EugeneSunrise** [comment]
> So, I saw that they're making a crack for the version 6.6 and I want to ask the owner if it's possible to make a crack for the version 6.7 since it has the Steam Deck Support.

6.7 is the same as 7.0 in terms of architecture, which means you will have to wait for the release of version 7.0

**Comment by EugeneSunrise** [comment]
CHECK README AND GIVE ME FEEDBACK

**Comment by EugeneSunrise** [comment]
Check releases and give me feedback

**Comment by EugeneSunrise** [comment]
6.6 ver ready, 7.0 will be later, any questions? Create NEW issue
