### ISSUE TITLE
cant download dll's

### ISSUE THREAD

**Issue by gngmoki** [EugeneSunrise/reWASD#14]
everytime i click on one of the two dll's it just takes me to VirusTotal and doesnt let me download in any kind of way, anyone else had this issue?

**Comment by bravazeroh** [comment]
you're clicking the wrong link, you need to click the links below "Assets" :D

**Comment by EugeneSunrise** [comment]
CHECK README AND GIVE ME FEEDBACK

**Comment by EugeneSunrise** [comment]
Check releases and give me feedback

**Comment by EugeneSunrise** [comment]
Check releases and give me feedback
