### ISSUE TITLE
Been a week and it's broken

### ISSUE THREAD

**Issue by gtxg16** [EugeneSunrise/reWASD#15]
So my trial ended, and i can get through to rewasd, but the controller and actual functionality of rewasd isnt there, its just broken. idk what to tell you

**Comment by Protoup20** [comment]
he's fixing it, give it time

**Comment by EugeneSunrise** [comment]
CHECK README AND GIVE ME FEEDBACK

**Comment by bravazeroh** [comment]
> CHECK README AND GIVE ME FEEDBACK

what would we need to do in order to setup 6.6? i'd rather have the program asap, but do what you gotta do

**Comment by EugeneSunrise** [comment]
> > CHECK README AND GIVE ME FEEDBACK
> 
> what would we need to do in order to setup 6.6? i'd rather have the program asap, but do what you gotta do

ok, wait guide

**Comment by SonnxyyxnnoS** [comment]
Approximately how long will it take until this works again

**Comment by EugeneSunrise** [comment]
Check releases

**Comment by EugeneSunrise** [comment]
and give me feedback

**Comment by EugeneSunrise** [comment]
6.6 ver ready, 7.0 will be later, any questions? Create NEW issue
