### ISSUE TITLE
Advanced features do not work for 6.6 | Now they do

### ISSUE THREAD

**Issue by bravazeroh** [EugeneSunrise/reWASD#16]
![image](https://github.com/EugeneSunrise/reWASD/assets/153247854/87ec4548-3df8-4b0f-ba22-7260bfe3e080)
I get this error upon applying a config

**Comment by bravazeroh** [comment]
> ![image](https://private-user-images.githubusercontent.com/153247854/291015217-87ec4548-3df8-4b0f-ba22-7260bfe3e080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NjA2MDksIm5iZiI6MTcwMjc2MDMwOSwicGF0aCI6Ii8xNTMyNDc4NTQvMjkxMDE1MjE3LTg3ZWM0NTQ4LTNkZjgtNGIwZi1iYTIyLTcyNjBiZmUzZTA4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQyMDU4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmU5NjEwZjZiN2JhYWVkYWJjMWY5M2Q5NGUwNzdkMDQyODcxZTMwYjEzMjUxZTk3YzE1OTFkZTM3NTc3OGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2riX_h-ook0mqICaH93DXJ2iTQ6IXTs9wr84qfzjEg8) I get this error upon applying a config

I'm very sure I didn't mess anything up as I've tangled with these programs before but I'll redownload just in case.

**Comment by EugeneSunrise** [comment]
> ![image](https://github.com/EugeneSunrise/reWASD/assets/153247854/87ec4548-3df8-4b0f-ba22-7260bfe3e080)
> 
> I get this error upon applying a config

Can you share your config? Maybe I forgot to add something to the crack... I'll check everything tomorrow and give an answer

**Comment by EugeneSunrise** [comment]
> > ![image](https://private-user-images.githubusercontent.com/153247854/291015217-87ec4548-3df8-4b0f-ba22-7260bfe3e080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NjA2MDksIm5iZiI6MTcwMjc2MDMwOSwicGF0aCI6Ii8xNTMyNDc4NTQvMjkxMDE1MjE3LTg3ZWM0NTQ4LTNkZjgtNGIwZi1iYTIyLTcyNjBiZmUzZTA4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQyMDU4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmU5NjEwZjZiN2JhYWVkYWJjMWY5M2Q5NGUwNzdkMDQyODcxZTMwYjEzMjUxZTk3YzE1OTFkZTM3NTc3OGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2riX_h-ook0mqICaH93DXJ2iTQ6IXTs9wr84qfzjEg8) I get this error upon applying a config
> 
> 
> 
> I'm very sure I didn't mess anything up as I've tangled with these programs before but I'll redownload just in case.

Does the remap not work at all or only with your config?

**Comment by bravazeroh** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/153247854/291015217-87ec4548-3df8-4b0f-ba22-7260bfe3e080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NjA2MDksIm5iZiI6MTcwMjc2MDMwOSwicGF0aCI6Ii8xNTMyNDc4NTQvMjkxMDE1MjE3LTg3ZWM0NTQ4LTNkZjgtNGIwZi1iYTIyLTcyNjBiZmUzZTA4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQyMDU4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmU5NjEwZjZiN2JhYWVkYWJjMWY5M2Q5NGUwNzdkMDQyODcxZTMwYjEzMjUxZTk3YzE1OTFkZTM3NTc3OGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2riX_h-ook0mqICaH93DXJ2iTQ6IXTs9wr84qfzjEg8) I get this error upon applying a config
> > 
> > 
> > I'm very sure I didn't mess anything up as I've tangled with these programs before but I'll redownload just in case.
> 
> Does the remap not work at all or only with your config?

Yes I can apply the config, but none of the advanced features work. Here's the config;
[config.zip](https://github.com/EugeneSunrise/reWASD/files/13693927/config.zip)

**Comment by EugeneSunrise** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/153247854/291015217-87ec4548-3df8-4b0f-ba22-7260bfe3e080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NjA2MDksIm5iZiI6MTcwMjc2MDMwOSwicGF0aCI6Ii8xNTMyNDc4NTQvMjkxMDE1MjE3LTg3ZWM0NTQ4LTNkZjgtNGIwZi1iYTIyLTcyNjBiZmUzZTA4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQyMDU4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmU5NjEwZjZiN2JhYWVkYWJjMWY5M2Q5NGUwNzdkMDQyODcxZTMwYjEzMjUxZTk3YzE1OTFkZTM3NTc3OGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2riX_h-ook0mqICaH93DXJ2iTQ6IXTs9wr84qfzjEg8) I get this error upon applying a config
> 
> > > 
> 
> > > 
> 
> > > I'm very sure I didn't mess anything up as I've tangled with these programs before but I'll redownload just in case.
> 
> > 
> 
> > Does the remap not work at all or only with your config?
> 
> 
> 
> Yes I can apply the config, but none of the advanced features work. Here's the config;
> 
> [config.zip](https://github.com/EugeneSunrise/reWASD/files/13693927/config.zip)
> 
> 

Ok, will fixed tomorrow

**Comment by EugeneSunrise** [comment]
At least something is already working... Not everything happens at once, my friends

**Comment by bravazeroh** [comment]
> At least something is already working... Not everything happens at once, my friends

Brother brother you doing us a massive favor no need to apologize, take your time!!

**Comment by Scriptmon** [comment]
First of, a massive thanks for your work!

I am getting the same error, the crack worked, however a similiar config I am using gives the same outcome.

Thanks again and a happy festive season

**Comment by SonnxyyxnnoS** [comment]
how long the crackt take?

**Comment by EugeneSunrise** [comment]
> how long the crackt take?

Already done, wait a little more, i will now update releases

**Comment by SonnxyyxnnoS** [comment]
yes, okay, because if I want to add a config it doesn't work and then it says something about buying

**Comment by EugeneSunrise** [comment]
FIX READY GO CHECK

**Comment by bravazeroh** [comment]
@EugeneSunrise It works! I am in-game right now and all of the features work. Telling you right now, if it isn't working for someone, they did something wrong during the setup. Thanks!

**Comment by EugeneSunrise** [comment]
> @EugeneSunrise It works! I am in-game right now and all of the features work. Telling you right now, if it isn't working for someone, they did something wrong during the setup. Thanks!

❤️
