### ISSUE TITLE
Download being flagged

### ISSUE THREAD

**Issue by smiggle7** [EugeneSunrise/reWASD#17]
When trying to download the latest version my pc flags it as a severe trojan and I am unable to download it

**Comment by EugeneSunrise** [comment]
> When trying to download the latest version my pc flags it as a severe trojan and I am unable to download it

It's because of dnSpy.exe in archive, You can try download dnSpy from source github profile(this is software for decompile .net programs) and You will also get red flag. If you think it's a virus, you can just not download
