### ISSUE TITLE
configs not loading

### ISSUE THREAD

**Issue by vuksahd** [EugeneSunrise/reWASD#20]
so when I try opening my config, nothing is there. I mean it opens and make a new profile but nothing is there not a single button or anything set up

**Comment by EugeneSunrise** [comment]
Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)

**Comment by bravazeroh** [comment]
> Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)

The config I sent you earlier in the zip file was made in 7.0, importing it works for me. I remember it having radial menu

**Comment by vuksahd** [comment]
> Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)

yeah the config is for version 7.0 will there be a crack for ver 7.0?

**Comment by vuksahd** [comment]
> > Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)
> 
> The config I sent you earlier in the zip file was made in 7.0, importing it works for me. I remember it having radial menu

do you know maybe how to use it even though its from version 7.0?

**Comment by EugeneSunrise** [comment]
> > Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)
> 
> yeah the config is for version 7.0 will there be a crack for ver 7.0?

there are some problems with 7.0 version, crack for 7.0 will be later

**Comment by bravazeroh** [comment]
> > > Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)
> 
> > 
> 
> > The config I sent you earlier in the zip file was made in 7.0, importing it works for me. I remember it having radial menu
> 
> 
> 
> do you know maybe how to use it even though its from version 7.0?
> 
> 

I imported it by 2x clicking on the .rewasd config file and everything was there except obviously radial menu, I didn't do anything special to make it work

**Comment by EugeneSunrise** [comment]
> > > Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)
> > 
> > 
> > The config I sent you earlier in the zip file was made in 7.0, importing it works for me. I remember it having radial menu
> 
> do you know maybe how to use it even though its from version 7.0?

send me your cfg

**Comment by vuksahd** [comment]
> > > > Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)
> > > 
> > > 
> > > The config I sent you earlier in the zip file was made in 7.0, importing it works for me. I remember it having radial menu
> > 
> > 
> > do you know maybe how to use it even though its from version 7.0?
> 
> send me your cfg

i will send u it with rar because I cant attach .rewasd files

**Comment by vuksahd** [comment]
> > > > Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)
> > > 
> > > 
> > > The config I sent you earlier in the zip file was made in 7.0, importing it works for me. I remember it having radial menu
> > 
> > 
> > do you know maybe how to use it even though its from version 7.0?
> 
> send me your cfg

here you go, its from this link https://cdn.discordapp.com/attachments/1143894845522444389/1185600661090484316/GoTwin__AAPlus.rewasd?ex=659033a8&is=657dbea8&hm=c3e101152845a1620732153e71d6abd3f1e978b909c66d502e1dc9bda0115568&

**Comment by EugeneSunrise** [comment]
> > > > > Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)
> > > > 
> > > > 
> > > > The config I sent you earlier in the zip file was made in 7.0, importing it works for me. I remember it having radial menu
> > > 
> > > 
> > > do you know maybe how to use it even though its from version 7.0?
> > 
> > 
> > send me your cfg
> 
> here you go, its from this link https://cdn.discordapp.com/attachments/1143894845522444389/1185600661090484316/GoTwin__AAPlus.rewasd?ex=659033a8&is=657dbea8&hm=c3e101152845a1620732153e71d6abd3f1e978b909c66d502e1dc9bda0115568&

yeah, ive checked and after import nothing happens, actually i dont know why is happens, but why you just can manual create config like yours?

**Comment by vuksahd** [comment]
> > > > > > Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)
> > > > > 
> > > > > 
> > > > > The config I sent you earlier in the zip file was made in 7.0, importing it works for me. I remember it having radial menu
> > > > 
> > > > 
> > > > do you know maybe how to use it even though its from version 7.0?
> > > 
> > > 
> > > send me your cfg
> > 
> > 
> > here you go, its from this link https://cdn.discordapp.com/attachments/1143894845522444389/1185600661090484316/GoTwin__AAPlus.rewasd?ex=659033a8&is=657dbea8&hm=c3e101152845a1620732153e71d6abd3f1e978b909c66d502e1dc9bda0115568&
> 
> yeah, ive checked and after import nothing happens, actually i dont know why is happens, but why you just can manual create config like yours?

its not my personal config, tbh I have no clue how to use rewasd or anything

**Comment by EugeneSunrise** [comment]
> > > > > > > Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)
> > > > > > 
> > > > > > 
> > > > > > The config I sent you earlier in the zip file was made in 7.0, importing it works for me. I remember it having radial menu
> > > > > 
> > > > > 
> > > > > do you know maybe how to use it even though its from version 7.0?
> > > > 
> > > > 
> > > > send me your cfg
> > > 
> > > 
> > > here you go, its from this link https://cdn.discordapp.com/attachments/1143894845522444389/1185600661090484316/GoTwin__AAPlus.rewasd?ex=659033a8&is=657dbea8&hm=c3e101152845a1620732153e71d6abd3f1e978b909c66d502e1dc9bda0115568&
> > 
> > 
> > yeah, ive checked and after import nothing happens, actually i dont know why is happens, but why you just can manual create config like yours?
> 
> its not my personal config, tbh I have no clue how to use rewasd or anything

Then find out the settings from the one who made this config or you can ask the person who has a license for 7.0 version and ask him the settings of your config

**Comment by EugeneSunrise** [comment]
> > > > > > > Maybe you used version 7.0 before and maybe the config for version 7.0 can't be loaded for version 6.6, but that's just my guess, importing profiles definitely works(based on user expirience)
> > > > > > 
> > > > > > 
> > > > > > The config I sent you earlier in the zip file was made in 7.0, importing it works for me. I remember it having radial menu
> > > > > 
> > > > > 
> > > > > do you know maybe how to use it even though its from version 7.0?
> > > > 
> > > > 
> > > > send me your cfg
> > > 
> > > 
> > > here you go, its from this link https://cdn.discordapp.com/attachments/1143894845522444389/1185600661090484316/GoTwin__AAPlus.rewasd?ex=659033a8&is=657dbea8&hm=c3e101152845a1620732153e71d6abd3f1e978b909c66d502e1dc9bda0115568&
> > 
> > 
> > yeah, ive checked and after import nothing happens, actually i dont know why is happens, but why you just can manual create config like yours?
> 
> its not my personal config, tbh I have no clue how to use rewasd or anything

Oh I know what you can do, install 7.0 version crack from releases(crack not work but you can check settings of your config and then install crack for 6.6 ver and setup your own config) :D

**Comment by EugeneSunrise** [comment]
I will close as completed
