### ISSUE TITLE
config doesn't work quickly, buy fire?

### ISSUE THREAD

**Issue by SonnxyyxnnoS** [EugeneSunrise/reWASD#21]

**Comment by SonnxyyxnnoS** [comment]
It says I have to buy fire quickly to use the config?
![Uploading Desktop Screenshot 2023.12.17 - 15.56.49.40.png…]()

**Comment by EugeneSunrise** [comment]
> It says I have to buy fire quickly to use the config?
> 
> 
> 
> 

Give me screenshot

**Comment by SonnxyyxnnoS** [comment]
how to send a screenshot

![Uploading Desktop Screenshot 2023.12.17 - 15.56.49.40.png…]()

**Comment by SonnxyyxnnoS** [comment]
Because whenever I wanted to start the config, I couldn't move my mouse and I had aimassist in-game, but now my mouse moves and it says that I should buy a Liziens

**Comment by bravazeroh** [comment]
did you by chance restart the program and forgot to launch it using dnSpy?

**Comment by SonnxyyxnnoS** [comment]
yes, I have restarted many times and it doesn't work. Maybe someone in discord can help me discord sonny_47

**Comment by EugeneSunrise** [comment]
> how to send a screenshot
> 
> 
> 
> ![Uploading Desktop Screenshot 2023.12.17 - 15.56.49.40.png…]()
> 
> 
You got something like this?
![image](https://github.com/EugeneSunrise/reWASD/assets/56397706/d65acacc-2c05-4fe8-993c-7a833d05f7db)

**Comment by SonnxyyxnnoS** [comment]
yes yes exactly that

**Comment by EugeneSunrise** [comment]
> 
> 
> yes yes exactly that
> 
> 
> 
> 

Bro, you use old breakpoint file, i uploaded release, please read what i wrote in description in release

**Comment by EugeneSunrise** [comment]
> 
> 
> yes yes exactly that
> 
> 
> 
> 

Only the breakpoint file has changed, NOW WE HAVE 4 BREAKPOINTS AND ALSO NOW 4 PATHES FOR reWASDEngine.exe file need to be changed (in the last release only 1 path needed to be changed). If you don't understand something, create a new task and describe your problem, also if you have problems with reWASD version 6.6 installation -> See completed tasks, also later I will update the text guide

**Comment by SonnxyyxnnoS** [comment]
oh okey i try thank you

**Comment by SonnxyyxnnoS** [comment]
But I don't understand how to change it now because I did it like in the video, only I did it with all 3 but it's the same. Maybe you can help me in discord via vc?

**Comment by EugeneSunrise** [comment]
> But I don't understand how to change it now because I did it like in the video, only I did it with all 3 but it's the same. Maybe you can help me in discord via vc?

I'm not at home right now and I can't go to discord, send me the breakpoint file you downloaded and your path to the rewasd engine

**Comment by SonnxyyxnnoS** [comment]
it works, thank you, I misunderstood something, I'm sorry for being so pushy, thank you

**Comment by EugeneSunrise** [comment]
> 
> 
> it works, thank you, I misunderstood something, I'm sorry for being so pushy, thank you

❤️
