### ISSUE TITLE
DnSpy Breakpoint issue.

### ISSUE THREAD

**Issue by OminousWeyland** [EugeneSunrise/reWASD#24]
![Capture](https://github.com/EugeneSunrise/reWASD/assets/154081334/774ca308-32d9-48cf-a4c9-d842e012ea05)

**Comment by OminousWeyland** [comment]
When I try to load the breakpoint it appears that.

**Comment by EugeneSunrise** [comment]
> When I try to load the breakpoint it appears that.
> 
> 

Looks like you broke breakpoint file, maybe you indicated the wrong path, the "symbol D" error on the screen, double-check the file with breakpoints, and it's better to do it first (unpack the archive with the files into the rewasd folder and so on, also reread the readme, I updated it an hour ago)

**Comment by OminousWeyland** [comment]
i WILL TRy again ig

**Comment by OminousWeyland** [comment]
I copyed the exact location tho

**Comment by OminousWeyland** [comment]
Still doesn't do anything, what the..

**Comment by EugeneSunrise** [comment]
> Still doesn't do anything, what the..

Same error or what? I need more info to help you...

**Comment by OminousWeyland** [comment]
Like I retyped the location you know, and it gives the exact same thing.

**Comment by OminousWeyland** [comment]
Also I don't understand a thing, the older file had like 2 breakpoints, this new one I got has only 1 is it fine?

**Comment by EugeneSunrise** [comment]
> Also I don't understand a thing, the older file had like 2 breakpoints, this new one I got has only 1 is it fine?

Brother, please, read readme(its preview of repo)🙏🏿🙏🏿🙏🏿

**Comment by EugeneSunrise** [comment]
"Applying config and nothing happens" read this in readme

**Comment by EugeneSunrise** [comment]
> Also I don't understand a thing, the older file had like 2 breakpoints, this new one I got has only 1 is it fine?

Older file - 1 breakpoint
New file - 4 breakpoints

**Comment by OminousWeyland** [comment]
I retyped the location man, it still doesn't do anything. I replaced the files. I am just going crazy.

**Comment by EugeneSunrise** [comment]
> I retyped the location man, it still doesn't do anything. I replaced the files. I am just going crazy.

Ok, send me there your text in breakpoint file and your path to reWASEngine.exe

**Comment by OminousWeyland** [comment]
![image](https://github.com/EugeneSunrise/reWASD/assets/154081334/40eb8988-6c9f-4dbb-9e3d-86c0267c633c)

<?xml version="1.0" encoding="utf-8"?>
<settings>
  <section _="fbc6039c-8a7a-49dc-9c32-52c1b73de0a3">
    <section _="Breakpoint" IsEnabled="True">
      <section _="BPL" __BPT="DotNet" AssemblyFullName="reWASDEngine, Version=6.6.0.7726, Culture=neutral, PublicKeyToken=null" Method="System.Void XBEliteWPF.Services.GamepadService/&lt;EnableRemap&gt;d__244::MoveNext()" ModuleName="D:\REWASD\reWASDEngine.exe" Offset="289" Token="100665914" />
      <section _="Trace" Message="$FUNCTION fucker1: {checkLicense=false}" />
    </section>
    <section _="Breakpoint" IsEnabled="True">
      <section _="BPL" __BPT="DotNet" AssemblyFullName="reWASDEngine, Version=6.6.0.7726, Culture=neutral, PublicKeyToken=null" Method="System.Boolean XBEliteWPF.License.LicenseMainVM::IsFeatureActivated(System.String)" ModuleName="D:\REWASD\reWASDEngine.exe" Offset="0" Token="100666840" />
      <section _="HitCount" Count="2" Kind="GreaterThanOrEquals" />
      <section _="Trace" Message="$FUNCTION fucker2:  {LicenseMainVM.instanceInfo.FeaturesCount=10}" />
    </section>
    <section _="Breakpoint" IsEnabled="True">
      <section _="BPL" __BPT="DotNet" AssemblyFullName="reWASDEngine, Version=6.6.0.7726, Culture=neutral, PublicKeyToken=null" Method="System.Boolean XBEliteWPF.License.LicenseMainVM::IsFeatureActivated(System.String)" ModuleName="D:\REWASD\reWASDEngine.exe" Offset="4" Token="100666840" />
      <section _="Trace" Message="$FUNCTION fucker3: {LicenseMainVM.instanceInfo.FeaturesStates[i].pszFeatureId=featureGuid}" />
    </section>
    <section _="Breakpoint" IsEnabled="True">
      <section _="BPL" __BPT="DotNet" AssemblyFullName="reWASDEngine, Version=6.6.0.7726, Culture=neutral, PublicKeyToken=null" Method="System.Boolean XBEliteWPF.License.LicenseMainVM::IsFeatureActivated(XBEliteWPF.License.Licensing.Enums.FeatureLicenseStatus,System.Int32)" ModuleName="D:\REWASD\reWASDEngine.exe" Offset="0" Token="100666841" />
      <section _="Trace" Message="$FUNCTION fucker4: {status=FeatureLicenseStatus.flsTrial} $FUNCTION1 fucker5: {trialDaysLeft=1337}" />
    </section>
  </section>
</settings>

**Comment by OminousWeyland** [comment]
<?xml version="1.0" encoding="utf-8"?>
<settings>
  <section _="fbc6039c-8a7a-49dc-9c32-52c1b73de0a3">
    <section _="Breakpoint" IsEnabled="True">
      <section _="BPL" __BPT="DotNet" AssemblyFullName="reWASDEngine, Version=6.6.0.7726, Culture=neutral, PublicKeyToken=null" Method="System.Void XBEliteWPF.Services.GamepadService/&lt;EnableRemap&gt;d__244::MoveNext()" ModuleName="D:\REWASD\reWASDEngine.exe" Offset="289" Token="100665914" />
      <section _="Trace" Message="$FUNCTION fucker1: {checkLicense=false}" />
    </section>
    <section _="Breakpoint" IsEnabled="True">
      <section _="BPL" __BPT="DotNet" AssemblyFullName="reWASDEngine, Version=6.6.0.7726, Culture=neutral, PublicKeyToken=null" Method="System.Boolean XBEliteWPF.License.LicenseMainVM::IsFeatureActivated(System.String)" ModuleName="D:\REWASD\reWASDEngine.exe" Offset="0" Token="100666840" />
      <section _="HitCount" Count="2" Kind="GreaterThanOrEquals" />
      <section _="Trace" Message="$FUNCTION fucker2:  {LicenseMainVM.instanceInfo.FeaturesCount=10}" />
    </section>
    <section _="Breakpoint" IsEnabled="True">
      <section _="BPL" __BPT="DotNet" AssemblyFullName="reWASDEngine, Version=6.6.0.7726, Culture=neutral, PublicKeyToken=null" Method="System.Boolean XBEliteWPF.License.LicenseMainVM::IsFeatureActivated(System.String)" ModuleName="D:\REWASD\reWASDEngine.exe" Offset="4" Token="100666840" />
      <section _="Trace" Message="$FUNCTION fucker3: {LicenseMainVM.instanceInfo.FeaturesStates[i].pszFeatureId=featureGuid}" />
    </section>
    <section _="Breakpoint" IsEnabled="True">
      <section _="BPL" __BPT="DotNet" AssemblyFullName="reWASDEngine, Version=6.6.0.7726, Culture=neutral, PublicKeyToken=null" Method="System.Boolean XBEliteWPF.License.LicenseMainVM::IsFeatureActivated(XBEliteWPF.License.Licensing.Enums.FeatureLicenseStatus,System.Int32)" ModuleName="D:\REWASD\reWASDEngine.exe" Offset="0" Token="100666841" />
      <section _="Trace" Message="$FUNCTION fucker4: {status=FeatureLicenseStatus.flsTrial} $FUNCTION1 fucker5: {trialDaysLeft=1337}" />
    </section>
  </section>
</settings>

**Comment by OminousWeyland** [comment]
i CAN'T send the code somehow

**Comment by OminousWeyland** [comment]
![image](https://github.com/EugeneSunrise/reWASD/assets/154081334/fb52eaf7-f78f-478f-b013-de5685626252)

**Comment by EugeneSunrise** [comment]
> ![image](https://github.com/EugeneSunrise/reWASD/assets/154081334/fb52eaf7-f78f-478f-b013-de5685626252)
> 
> 

Still the same error? "D" ?

**Comment by OminousWeyland** [comment]
WAIT IT LOADED

**Comment by OminousWeyland** [comment]
![image](https://github.com/EugeneSunrise/reWASD/assets/154081334/df50ee0c-8375-46b5-9dbb-594498425af0)

**Comment by EugeneSunrise** [comment]
> ![image](https://github.com/EugeneSunrise/reWASD/assets/154081334/df50ee0c-8375-46b5-9dbb-594498425af0)
> 
> 

Finally u did it🏅

**Comment by OminousWeyland** [comment]
Now.

**Comment by OminousWeyland** [comment]
I have to run it and that's it right

**Comment by EugeneSunrise** [comment]
> I have to run it and that's it right

Yes

**Comment by OminousWeyland** [comment]
Okay it works! Thank you so much man and if I want to start it again I repeat the same process right?

**Comment by OminousWeyland** [comment]
iF I want to close it do I stop the script itself? Or I close both programs?

**Comment by EugeneSunrise** [comment]
Launch ONLY from dnSpy(actually dnSpy save your work and u dont need to do it every time, just start dnSpy, choose reWASDEngine in assembly editor in left top coner) and push start button, when you want to close reWASD, just do it from tray icon, dnSpy automatically stops and then you can close dnSpy

**Comment by EugeneSunrise** [comment]
If i answered all your questions, close issue as completed🎗️
