### ISSUE TITLE
Advanced features don't work

### ISSUE THREAD

**Issue by AyeeSecret** [EugeneSunrise/reWASD#25]
Reinstalled multiple times, features like Rapid Fire or Advanced Remapping don't work
![image](https://github.com/EugeneSunrise/reWASD/assets/70549690/852cbd9c-510c-49df-b921-1447ba95a592)

**Comment by EugeneSunrise** [comment]
> Reinstalled multiple times, features like Rapid Fire or Advanced Remapping don't work
> 
> ![image](https://github.com/EugeneSunrise/reWASD/assets/70549690/852cbd9c-510c-49df-b921-1447ba95a592)
> 
> 

Bro, didn't you fix it? Check last open issue

**Comment by EugeneSunrise** [comment]
You dont need to reinstall it multiple times, you just need 4 breakpoints in dnSpy for correct work

**Comment by AyeeSecret** [comment]
> > Reinstalled multiple times, features like Rapid Fire or Advanced Remapping don't work
> > ![image](https://private-user-images.githubusercontent.com/70549690/291102873-852cbd9c-510c-49df-b921-1447ba95a592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDQxMDgsIm5iZiI6MTcwMjg0MzgwOCwicGF0aCI6Ii83MDU0OTY5MC8yOTExMDI4NzMtODUyY2JkOWMtNTEwYy00OWRmLWI5MjEtMTQ0N2JhOTVhNTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDIwMTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOTlhYjRiNWM0NzRhMjYyMTgxODE4NTA4NDMwZGU1YWNhOGQwNzhmZmVhMzFiZjc4MzBjNDJiYTM3NTk1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PHubNw0VjA98G_m_xDC2tbZ_5TeD_Q8C0OH7YSsWSv8)
> 
> Bro, didn't you fix it? Check last open issue

That was to apply configs, configs now work but advanced features don't. I have the 4 breakpoints active, and it is still not working

**Comment by EugeneSunrise** [comment]
> > > Reinstalled multiple times, features like Rapid Fire or Advanced Remapping don't work
> 
> > > ![image](https://private-user-images.githubusercontent.com/70549690/291102873-852cbd9c-510c-49df-b921-1447ba95a592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDQxMDgsIm5iZiI6MTcwMjg0MzgwOCwicGF0aCI6Ii83MDU0OTY5MC8yOTExMDI4NzMtODUyY2JkOWMtNTEwYy00OWRmLWI5MjEtMTQ0N2JhOTVhNTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDIwMTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOTlhYjRiNWM0NzRhMjYyMTgxODE4NTA4NDMwZGU1YWNhOGQwNzhmZmVhMzFiZjc4MzBjNDJiYTM3NTk1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PHubNw0VjA98G_m_xDC2tbZ_5TeD_Q8C0OH7YSsWSv8)
> 
> > 
> 
> > Bro, didn't you fix it? Check last open issue
> 
> 
> 
> That was to apply configs, configs now work but advanced features don't. I have the 4 breakpoints active, and it is still not working

Send me screenshot of 4 breakpoints while debug

**Comment by AyeeSecret** [comment]
> > > > Reinstalled multiple times, features like Rapid Fire or Advanced Remapping don't work
> > 
> > 
> > > > ![image](https://private-user-images.githubusercontent.com/70549690/291102873-852cbd9c-510c-49df-b921-1447ba95a592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDQxMDgsIm5iZiI6MTcwMjg0MzgwOCwicGF0aCI6Ii83MDU0OTY5MC8yOTExMDI4NzMtODUyY2JkOWMtNTEwYy00OWRmLWI5MjEtMTQ0N2JhOTVhNTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDIwMTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOTlhYjRiNWM0NzRhMjYyMTgxODE4NTA4NDMwZGU1YWNhOGQwNzhmZmVhMzFiZjc4MzBjNDJiYTM3NTk1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PHubNw0VjA98G_m_xDC2tbZ_5TeD_Q8C0OH7YSsWSv8)
> > 
> > 
> > > 
> > 
> > 
> > > Bro, didn't you fix it? Check last open issue
> > 
> > 
> > That was to apply configs, configs now work but advanced features don't. I have the 4 breakpoints active, and it is still not working
> 
> Send me screenshot of 4 breakpoints while debug

 I was missing one \ in the breakpoint, I only had 3 active. Sorry to bother you

**Comment by EugeneSunrise** [comment]
> > > > > Reinstalled multiple times, features like Rapid Fire or Advanced Remapping don't work
> 
> > > 
> 
> > > 
> 
> > > > > ![image](https://private-user-images.githubusercontent.com/70549690/291102873-852cbd9c-510c-49df-b921-1447ba95a592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDQxMDgsIm5iZiI6MTcwMjg0MzgwOCwicGF0aCI6Ii83MDU0OTY5MC8yOTExMDI4NzMtODUyY2JkOWMtNTEwYy00OWRmLWI5MjEtMTQ0N2JhOTVhNTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDIwMTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOTlhYjRiNWM0NzRhMjYyMTgxODE4NTA4NDMwZGU1YWNhOGQwNzhmZmVhMzFiZjc4MzBjNDJiYTM3NTk1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PHubNw0VjA98G_m_xDC2tbZ_5TeD_Q8C0OH7YSsWSv8)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Bro, didn't you fix it? Check last open issue
> 
> > > 
> 
> > > 
> 
> > > That was to apply configs, configs now work but advanced features don't. I have the 4 breakpoints active, and it is still not working
> 
> > 
> 
> > Send me screenshot of 4 breakpoints while debug
> 
> 
> 
>  I was missing one \ in the breakpoint, I only had 3 active. Sorry to bother you

Is it work now? If all good, close issue as completed❤️ Actually, i recommend to read current open issue with name "Dnspy breakpoints.." in the end of issue i wrote about launch and close dnspy with rewasd
