### ISSUE TITLE
Perfect run in V 6.6

### ISSUE THREAD

**Issue by rockyuuuuu** [EugeneSunrise/reWASD#26]
Perfect run in V 6.6, just in the video it indicated start only from dnspy, so each time I need open dnspy and click run button to run rewasd.
is it possible to make an autostart when I start my computer? then rewasd can be run automaticly in minimize Window to Tray Menu when I start window, thanks

**Comment by EugeneSunrise** [comment]
> Perfect run in V 6.6, just in the video it indicated start only from dnspy, so each time I need open dnspy and click run button to run rewasd.
> 
> is it possible to make an autostart when I start my computer? then rewasd can be run automaticly in minimize Window to Tray Menu when I start window, thanks

Unfortunately, it is probably impossible to automate the process, because dnSpy does not have an api, in any case, if I figure out how to automate the process, I will relend the script

**Comment by rockyuuuuu** [comment]
Following my question, I found a solution specific for me, I use autohotkey, made a simple file including lines below, and move it to startup folder, then it can be automaticly run when I start PC and placed in tray menu:)

Thank you again

Run, D:\reWASD1\dnSpy-net-win32\dnSpy.exe
Sleep 3000
Send {F5}
Sleep 2000
Send {Enter}
Sleep 1000
Winhide dnSpy

**Comment by EugeneSunrise** [comment]
> Following my question, I found a solution specific for me, I use autohotkey, made a simple file including lines below, and move it to startup folder, then it can be automaticly run when I start PC and placed in tray menu:)
> 
> 
> 
> Thank you again
> 
> 
> 
> Run, D:\reWASD1\dnSpy-net-win32\dnSpy.exe
> 
> Sleep 3000
> 
> Send {F5}
> 
> Sleep 2000
> 
> Send {Enter}
> 
> Sleep 1000
> 
> Winhide dnSpy

Very good, I'll add your answer to readme, thank you
