### ISSUE TITLE
installed correctly, followed video guide... but remap does nothing.

### ISSUE THREAD

**Issue by maxi-pc** [EugeneSunrise/reWASD#27]
when I launched via dnspy I can see rewasd, cracked by etc.

I setup my profiles, launch game I see "remap.." notification, but actually NOTHING is remapped.

my PS5 controller is still PS5 controller on windows (gamePad) and in gamepad tester page here https://hardwaretester.com/gamepad

It does not create virtual controller and switch off my PS5 controller :(

**Comment by Jabata312** [comment]
i have the same poroblem

**Comment by EugeneSunrise** [comment]
You guys haven't checked to README... Don't upset me, I'm already tired of explaining everything to everyone, today a little later I will publish a text guide for the especially gifted

**Comment by maxi-pc** [comment]
> You guys haven't checked to README... Don't upset me, I'm already tired of explaining everything to everyone, today a little later I will publish a text guide for the especially gifted

Matter of fact, I read the readme as of 18/12/2023 and watched your "guide" video.

The path for engine file on the XML is the same as the path I have on my current, literally same path location so I have no need to change anything.

If I didn't follow the steps correctly, then I wouldn't be able to add the cracked version of the exe with the link to your GitHub.

**Comment by maxi-pc** [comment]
https://www.youtube.com/watch?v=gB-v8Ys0U24 still not working, same steps as "noob" video and text guide.
