### ISSUE TITLE
I think its from the crack 

### ISSUE THREAD

**Issue by Jabata312** [EugeneSunrise/reWASD#28]
Hey i have a problem with the rewasd with the crack 
When i apply slots and click remap on nothing happend like its not remap on its like off and thats on every config
With normal rewasd without crack the config work i don t know why this happend if someone know how to  fixed just write

**Comment by EugeneSunrise** [comment]
You guys haven't checked to README... Don't upset me, I'm already tired of explaining everything to everyone, today a little later I will publish a text guide for the especially gifted

**Comment by Jabata312** [comment]
I read read me and make anything but when remap is on
Yesterday when i click remap on i cant move my mouse and everything works

**Comment by Jabata312** [comment]
Sorry for my bad english

**Comment by Jabata312** [comment]
And now when i click remap on i can move my mouse and keyboard

**Comment by EugeneSunrise** [comment]
> And now when i click remap on i can move my mouse and keyboard 

Launch only from dnSpy and you cant close dnSpy while rewasd is work!

**Comment by Jabata312** [comment]
> from

I know i launched form dnspy and when i click remap on i can move my mouse and keyboard

**Comment by EugeneSunrise** [comment]
> > from
> 
> I know i launched form dnspy and when i click remap on i can move my mouse and keyboard 

Send me screenshot of breakpoints in dnSpy

**Comment by Jabata312** [comment]
> > > from
> > 
> > I know i launched form dnspy and when i click remap on i can move my mouse and keyboard 
> 
> Send me screenshot of breakpoints in dnSpy

Ok but i need to get at home

**Comment by bravazeroh** [comment]
> > from
> 
> I know i launched form dnspy and when i click remap on i can move my mouse and keyboard 

some configs allow mouse movement on default, some block mouse movement to prevent double input. did you apply the correct config?

**Comment by Jabata312** [comment]
> > > from
> > 
> > I know i launched form dnspy and when i click remap on i can move my mouse and keyboard 
> 
> some configs allow mouse movement on default, some block mouse movement to prevent double input. did you apply the correct config?

Yes in every config i have i can move mouse but actually in the config i cant move my mouse

**Comment by bravazeroh** [comment]
> > > > from
> > > 
> > > I know i launched form dnspy and when i click remap on i can move my mouse and keyboard 
> > 
> > some configs allow mouse movement on default, some block mouse movement to prevent double input. did you apply the correct config?
> 
> Yes in every config i have i can move mouse but actually in the config i cant move my mouse 

i'm so confused, so if you cant move ur mouse it means the config works u just need to find the bind to enable mouse movement.

**Comment by Jabata312** [comment]
> > > > > from
> > > > 
> > > > I know i launched form dnspy and when i click remap on i can move my mouse and keyboard 
> > > 
> > > some configs allow mouse movement on default, some block mouse movement to prevent double input. did you apply the correct config?
> > 
> > Yes in every config i have i can move mouse but actually in the config i cant move my mouse 
> 
> i'm so confused, so if you cant move ur mouse it means the config works u just need to find the bind to enable mouse movement.

Uh i dont know how to explain to you 
The config works but i can move my mouse
And when i click some button to change a layer the layer not changing

**Comment by EugeneSunrise** [comment]
Updated text guide in readme and added second guide video
