### ISSUE TITLE
Doesn't seem to work on reWASD670-8052

### ISSUE THREAD

**Issue by ericwgarza1** [EugeneSunrise/reWASD#3]
just as title says....I replaced the two files in the installation folder and the configuration screen would no longer come up and trial was showing as expired. Build 8052 (latest) directly from their website is different thatn the  build you have posted as welll. Maybe thats the issue.

**Comment by EugeneSunrise** [comment]
Any questions?

**Comment by HitmanAgentICA47** [comment]
Hello. First of all thanks for giving a chance to get this program, since it's unavailable for me. I hope the one for Windows will be released soon. 😊

**Comment by V0ltZz** [comment]
also made an acc just to ask

**Comment by EugeneSunrise** [comment]
> > Any questions?
> 
> yes, alot of questions but lemme summarize them Can i get a tut plz?

I've updated readme of repo, check https://github.com/EugeneSunrise/reWASD

**Comment by EugeneSunrise** [comment]
Ask me if u still have any questions

**Comment by SnapdragonLee** [comment]
I want to say how to get the original code? I wanna create versions for x86/x64

**Comment by EugeneSunrise** [comment]
> I want to say how to get the original code? I wanna create versions for x86/x64

You can download the repository and try to restore all the links, but it won't be easy

**Comment by EugeneSunrise** [comment]
If you still have questions, please open a new issue or message me on telegram
