### ISSUE TITLE
reWASD700-8447(x64/x86)

### ISSUE THREAD

**Issue by Jaayaz** [EugeneSunrise/reWASD#30]
my license time is up and the crack isn't working

**Comment by EugeneSunrise** [comment]
7.0 ver not workinf right now, install 6.6ver or wait fix for 7.0, close issue if I answered all your questions

**Comment by Jaayaz** [comment]
I need to do all the procedures for both tabs so that rewasd crack can work?

**Comment by EugeneSunrise** [comment]
> I need to do all the procedures for both tabs so that rewasd crac

For 6.6 ver check youtube guide
