### ISSUE TITLE
does not create virtual controllers.

### ISSUE THREAD

**Issue by maxi-pc** [EugeneSunrise/reWASD#31]
https://www.youtube.com/watch?v=gB-v8Ys0U24

**Comment by EugeneSunrise** [comment]
> https://www.youtube.com/watch?v=gB-v8Ys0U24

I watched the video, first try to apply another simple cogfig without gamepad (for example, on a mouse to just check the performance)

**Comment by EugeneSunrise** [comment]
In addition, it is possible that your configuration simply does not work for version 6.6. You need to find someone who also has dualsense and test it on versions 6.6 and 7. I don't have any gamepad, but some people who asked me for help, they had gamepads and everything worked fine

**Comment by Leclowndu93150** [comment]
hmm same for me, i wasn't able to do remoteplay today, is there any way i can install an older crack of rewasd ?

**Comment by EugeneSunrise** [comment]
> hmm same for me, i wasn't able to do remoteplay today, is there any way i can install an older crack of rewasd ?

only wait crack for 7.0 ver

**Comment by Leclowndu93150** [comment]
im not trying to be annoying but do you have any ETA ?
Thanks for the work, much appreciated

**Comment by EugeneSunrise** [comment]
> im not trying to be annoying but do you have any ETA ?
> 
> Thanks for the work, much appreciated

There is a problem that I encountered during the cracking 7th version, as soon as it is solved and I will release, we are also waiting any news from another developer (Eddy), I hope he will succeed and I will not have to dig into the code :D. There is no release date, because I just finished cracking the 6.6 version, it took many time and also now I am constantly being sent for installation help, so I think we should expect the 7th version next year

**Comment by Leclowndu93150** [comment]
oh damn thats in a long time  but good luck !

**Comment by Leclowndu93150** [comment]
Hey did u see the news ?![Screenshot_2023-12-23-08-27-12-691_com.reddit.frontpage.jpg](https://github.com/EugeneSunrise/reWASD/assets/73310949/6d71f51c-54a8-4c11-9f8a-f6a31bb42249)

**Comment by EugeneSunrise** [comment]
> Hey did u see the news ?![Screenshot_2023-12-23-08-27-12-691_com.reddit.frontpage.jpg](https://github.com/EugeneSunrise/reWASD/assets/73310949/6d71f51c-54a8-4c11-9f8a-f6a31bb42249)
> 
> 
I haven't seen the news itself, although it's strange, the fix is still in work
