### ISSUE TITLE
everything works except the actual thing  i used 2 diff configs but it dont work 

### ISSUE THREAD

**Issue by godh2** [EugeneSunrise/reWASD#32]

**Comment by EugeneSunrise** [comment]
What actual thing? Need more info...

**Comment by godh2** [comment]
wait ok

**Comment by godh2** [comment]
everyhting works i did everything u do but when i load a config nothing happens it says im on main layer and nothign works

**Comment by EugeneSunrise** [comment]
> everyhting works i did everything u do but when i load a config nothing happens it says im on main layer and nothign works 

if I understood everything correctly after importing config nothing happens most likely it means that the config was made on version 7 and it does not work 6.6, there were already such issues

**Comment by godh2** [comment]
oh ok

**Comment by EugeneSunrise** [comment]
> so do i have to make my own config? or do  i find 6.6 config?s

Yep, you need to do your own cfg, or just try another similar, or if you want only your cfg(that not works), you can install 7.0ver crack(not working remap) and check settings of config and remember them, if i answered all your questions, please, close issue as completed👻

**Comment by godh2** [comment]
ok
