### ISSUE TITLE
problem with virus

### ISSUE THREAD

**Issue by vuksahd** [EugeneSunrise/reWASD#34]
so, windows real time protection deleted my rewasd for a trojan. now when i try to reinstall it I get a error from rewasd "Error during install: -1" is it patched or?

**Comment by EugeneSunrise** [comment]
Have no any idea bro, there is no any viruses or other shit, just do full deinstalling rewasd, maybe defender checks dnSpy as kind of virus, but its normal for dnSpy, you can download manually from official repository

**Comment by bravazeroh** [comment]
> Have no any idea bro, there is no any viruses or other shit, just do full deinstalling rewasd, maybe defender checks dnSpy as kind of virus, but its normal for dnSpy, you can download manually from official repository 

it flags reWASD.exe as a trojan, prob a false positive flagged for me too a while ago
