### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by Saant7** [EugeneSunrise/reWASD#35]
man the antivirus says that the trojan is in the C file on my pc but the folder has already been deleted and where the anti virus says that the trojan is active and there is no folder I don't know why. what should i do

**Comment by Saant7** [comment]
In my antivirus history it says it is still active but there is nothing in the folder it indicates

**Comment by EugeneSunrise** [comment]
I will grab your browser history👻

**Comment by EugeneSunrise** [comment]
After you start the Trojan, your PC will explode

**Comment by EugeneSunrise** [comment]
Be careful bro
