### ISSUE TITLE
this guy use ur code to make money

### ISSUE THREAD

**Issue by SmallSideOUO** [EugeneSunrise/reWASD#37]
https://www.youtube.com/watch?v=gTb6cdRc1AM

**Comment by EugeneSunrise** [comment]
Yeah ahahahha i see

**Comment by EugeneSunrise** [comment]
What should I do? Open the video for everyone?

**Comment by CodeXz0** [comment]
> What should I do? Open the video for everyone?

You should always prompt that it's free every time you open it

**Comment by EugeneSunrise** [comment]
Open yt guides for all

**Comment by Tawnee323** [comment]
He deleted the offer lmao

**Comment by EugeneSunrise** [comment]
> He deleted the offer lmao

hahhahahah
