### ISSUE TITLE
Are These just false positives because of the Crack FIles

### ISSUE THREAD

**Issue by Demon0-0** [EugeneSunrise/reWASD#38]
![VT](https://github.com/EugeneSunrise/reWASD/assets/154615290/9943d705-0669-463c-9a15-74f43b58864c)

**Comment by EugeneSunrise** [comment]
> ![VT](https://github.com/EugeneSunrise/reWASD/assets/154615290/9943d705-0669-463c-9a15-74f43b58864c)
> 
> 

Its safe bro, trust me😈![image](https://github.com/EugeneSunrise/reWASD/assets/56397706/b9d42004-8e16-4556-880c-884a15d1b9af)

**Comment by Demon0-0** [comment]
Alright bro i came here from cs rin and i never had any Virus issues in that community so imma go with it.
