### ISSUE TITLE
About he version 7

### ISSUE THREAD

**Issue by BeginnerLJK** [EugeneSunrise/reWASD#40]
In version 7, when it is cracked, will we continue to have to use dnSpy to launch the application?

**Comment by ChetFromFalloutNewVegas** [comment]
Download sex

**Comment by EugeneSunrise** [comment]
> In version 7, when it is cracked, will we continue to have to use dnSpy to launch the application?

No dnSpy in 7ver. Jusr launch the app

**Comment by BeginnerLJK** [comment]
Awesome
