### ISSUE TITLE
I can’t replace rewasd

### ISSUE THREAD

**Issue by meekgod11** [EugeneSunrise/reWASD#42]
when I insert files from the archive changes everything except rewasd.exe what I do.
I put a checkmark when I could not replace rewasd.exe did not set and could not

**Comment by jajajajaaaaae** [comment]
it happened to me jst delete rewasd and drop the one from reWASD_6Ver_by_EugeneSunrise_WithLove in ur rewasd file

**Comment by EugeneSunrise** [comment]
> when I insert files from the ar

Maybe av blocks

**Comment by meekgod11** [comment]
what is av>

**Comment by EugeneSunrise** [comment]
> what is av>
> 
> 

antivirus

**Comment by meekgod11** [comment]
windows antivirus can be turned off?

**Comment by EugeneSunrise** [comment]
> windows antivirus can be turned off?

ofc, check google bro 😄

**Comment by meekgod11** [comment]
![image](https://github.com/EugeneSunrise/reWASD/assets/154662852/3a1d5a37-cf22-4468-a75b-cf40d12953b2) what the fuck

**Comment by EugeneSunrise** [comment]
> ![image](https://github.com/EugeneSunrise/reWASD/assets/154662852/3a1d5a37-cf22-4468-a75b-cf40d12953b2) what the fuck
Maybe rewasdEngine.exe is running or You don't have admin rights on the PC :D

**Comment by meekgod11** [comment]
:(
