### ISSUE TITLE
sorry my rewasd dosent work for some reason after restarting pc 

### ISSUE THREAD

**Issue by TeddyDepp** [EugeneSunrise/reWASD#44]
![image](https://github.com/EugeneSunrise/reWASD/assets/154688536/5eaec302-f6fa-47a6-9d3c-0efc22c59622)
idk what to do i did all the video steps

**Comment by EugeneSunrise** [comment]
> ![image](https://github.com/EugeneSunrise/reWASD/assets/154688536/5eaec302-f6fa-47a6-9d3c-0efc22c59622)
> 
> idk what to do i did all the video steps
> 
> 

Can you contact me in telegram? I will just resend messages with solution... tg: sunrjze

**Comment by EugeneSunrise** [comment]
> ![image](https://github.com/EugeneSunrise/reWASD/assets/154688536/5eaec302-f6fa-47a6-9d3c-0efc22c59622)
> 
> idk what to do i did all the video steps
> 
> 

Can you contact me in telegram? I will just resend messages with solution... tg: sunrjze

**Comment by TeddyDepp** [comment]
> > ![image](https://private-user-images.githubusercontent.com/154688536/292633186-5eaec302-f6fa-47a6-9d3c-0efc22c59622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDU1OTUsIm5iZiI6MTcwMzM0NTI5NSwicGF0aCI6Ii8xNTQ2ODg1MzYvMjkyNjMzMTg2LTVlYWVjMzAyLWY2ZmEtNDdhNi05ZDNjLTBlZmMyMmM1OTYyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNTI4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTAwMzFiYzM5OGI0MWU5NDM3NTE4YjI1NzM4MDY3N2U2YTFlYWViOGMyNzgyZWFhNDFmMWQwZjI3MWM5NTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hMDcS1VU4Q1enFgjAQDaPWJbWr5xKtrclNdv_57Jt-E)
> > idk what to do i did all the video steps
> 
> Can you contact me in telegram? I will just resend messages with solution... tg: sunrjze

yes of course my number is +20 10 6438 7156 and the qr
![qr_tmp](https://github.com/EugeneSunrise/reWASD/assets/154688536/0d026b0b-3f23-4e06-8662-7df06be284ba)

**Comment by EugeneSunrise** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/154688536/292633186-5eaec302-f6fa-47a6-9d3c-0efc22c59622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDU1OTUsIm5iZiI6MTcwMzM0NTI5NSwicGF0aCI6Ii8xNTQ2ODg1MzYvMjkyNjMzMTg2LTVlYWVjMzAyLWY2ZmEtNDdhNi05ZDNjLTBlZmMyMmM1OTYyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNTI4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTAwMzFiYzM5OGI0MWU5NDM3NTE4YjI1NzM4MDY3N2U2YTFlYWViOGMyNzgyZWFhNDFmMWQwZjI3MWM5NTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hMDcS1VU4Q1enFgjAQDaPWJbWr5xKtrclNdv_57Jt-E)
> > > idk what to do i did all the video steps
> > 
> > 
> > Can you contact me in telegram? I will just resend messages with solution... tg: sunrjze
> 
> yes of course my number is +20 10 6438 7156 and the qr ![qr_tmp](https://private-user-images.githubusercontent.com/154688536/292633546-0d026b0b-3f23-4e06-8662-7df06be284ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDU5MjgsIm5iZiI6MTcwMzM0NTYyOCwicGF0aCI6Ii8xNTQ2ODg1MzYvMjkyNjMzNTQ2LTBkMDI2YjBiLTNmMjMtNGUwNi04NjYyLTdkZjA2YmUyODRiYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNTMzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjAwNmQwMTU1MTFiNmFmYzBiN2ZlYzhlZjcxZTc4MjIzNTZhYTUxMzZkM2VmZWMzNWI3MmU3MmFjNmYwYTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pxFLGjhoRstl5enQ9HM117ct9gvZeYRV1nzi8o0Kbmo)

text me
