### ISSUE TITLE
a

### ISSUE THREAD

**Issue by jajajajaaaaae** [EugeneSunrise/reWASD#47]
so it worked fine until now but my shiit doesnt open when i start the breakpoint thing

**Comment by EugeneSunrise** [comment]
Need more info, screenshots etc, how can i help you if i even dont know what problem is?

**Comment by jajajajaaaaae** [comment]
![image](https://github.com/EugeneSunrise/reWASD/assets/151778873/12782f5b-4558-40e4-b81b-9c9a47cfaacd)
i do the same as the vid to launch rewasd but when i click start it just load then it doesnt open here:
![image](https://github.com/EugeneSunrise/reWASD/assets/151778873/21389453-e76b-428a-942c-f495b462f074)

**Comment by EugeneSunrise** [comment]
> ![image](https://github.com/EugeneSunrise/reWASD/assets/151778873/12782f5b-4558-40e4-b81b-9c9a47cfaacd)
> 
> i do the same as the vid to launch rewasd but when i click start it just load then it doesnt open here:
> 
> ![image](https://github.com/EugeneSunrise/reWASD/assets/151778873/21389453-e76b-428a-942c-f495b462f074)
> 
> 

Contact me know telegram, i will resend messages with solution, tg: @sunrjze

**Comment by Zizoplays1** [comment]
so since this is open, one question, do i have to launch dnspy and start the debug process everytime i want to launch rewasd? can't i just open rewasd normally?

**Comment by EugeneSunrise** [comment]
> so since this is open, one question, do i have to launch dnspy and start the debug process everytime i want to launch rewasd? can't i just open rewasd normally?

Yep, u need to launch dnspy and start the debug process everytime, u cant close dbspy when rewasd working, only hide window, u can close dnspy only after full closing rewasd from tray
