### ISSUE TITLE
Why is it detected trojan.avbdiscsoft

### ISSUE THREAD

**Issue by qwer99887** [EugeneSunrise/reWASD#48]
I detected it from this document trojan.avbdiscsoft  The detection link is below

https://www.virustotal.com/gui/file/92e0d01d5c51b1d61e70542f392c2dd80ee66aa2207a3a8bc78b04fdaf5dac5b

**Comment by EugeneSunrise** [comment]
> I detected it from this document trojan.avbdiscsoft  The detection link is below
> 
> 
> 
> 
> 
> https://www.virustotal.com/gui/file/92e0d01d5c51b1d61e70542f392c2dd80ee66aa2207a3a8bc78b04fdaf5dac5b

What do you want me to tell you?

**Comment by EugeneSunrise** [comment]
![image](https://github.com/EugeneSunrise/reWASD/assets/56397706/60527550-2081-4769-8ae9-6fa1e1b4a0b7)
