### ISSUE TITLE
THE BREAKINGPOINT FILE ISN'T WORKING

### ISSUE THREAD

**Issue by LuisAlbertodosSantos** [EugeneSunrise/reWASD#49]
When I try to import the breakingpoint file none of the four boxes appear and reWASDEngine does not display all the necessary information

**Comment by EugeneSunrise** [comment]
> When I try to import the breakingpoint file none of the four boxes appear and reWASDEngine does not display all the necessary information

Why don't you read the readme and immediately go to create an issue?
