### ISSUE TITLE
I did the correct tutorial but when I open rewasd I receive the message

### ISSUE THREAD

**Issue by rickdevcod** [EugeneSunrise/reWASD#50]
I'm accepting the same error, asking to update to the most updated version.

**Comment by EugeneSunrise** [comment]
Maybe you haven't replaced the files or not restarted the PC, I cut out all the windows with updates, they can't appear

**Comment by rickdevcod** [comment]
I managed it, thank you, but now I have another problem, I can't import control settings from other creators into my Rewasd, I don't think it can be imported due to the crack, right?

**Comment by EugeneSunrise** [comment]
> I managed it, thank you, but now I have another problem, I can't import control settings from other creators into

Some configs that were created on the latest versions may not work on the 6.6 version, although usually 7.0 version configs work on 6.6, you need to use another config or make your own config yourself

**Comment by rickdevcod** [comment]
yes, i imagine this, When will the update for the newer version come out? Do you think about doing it?

**Comment by EugeneSunrise** [comment]
Close issue if i answered all your questions

**Comment by EugeneSunrise** [comment]
> yes, i imagine this, When will the update for the newer version come out? Do you think about doing it?
> 
> 

Right now have no any eta, sry

**Comment by rickdevcod** [comment]
Ok, thanks, problem solved
