### ISSUE TITLE
cant put the 3 files into rewasd folder

### ISSUE THREAD

**Issue by szeress22** [EugeneSunrise/reWASD#53]
it says that for unknown reason i cant put the rewasd app that you put in the rewasd folder early in the video
![Képernyőfelvétel (21)](https://github.com/EugeneSunrise/reWASD/assets/155153400/271205a9-69ba-4ab8-ac50-768ee6148f7f)

**Comment by EugeneSunrise** [comment]
> it says that for unknown reason i cant put the rewasd app that you put in the rewasd folder early in the video
> 
> ![Képernyőfelvétel (21)](https://github.com/EugeneSunrise/reWASD/assets/155153400/271205a9-69ba-4ab8-ac50-768ee6148f7f)
> 
> 

Defender blocks files or you dont have admin privileges

**Comment by szeress22** [comment]
okey done it now but it says that i have to buy "advanced mapping and  rapid fire" to get full power

**Comment by EugeneSunrise** [comment]
> okey done it now but it says that i have to buy "advanced mapping and  rapid fire" to get full power
> 
> 

You need to have 4 breakpoints, you have only 1

**Comment by szeress22** [comment]
ty workin
