### ISSUE TITLE
Have to make another issue because it just got closed

### ISSUE THREAD

**Issue by dahcat1** [EugeneSunrise/reWASD#55]
i did literally everything shown in the video, including changing the folders inside of the xml + adding it to rewasdengine.exe by using "import breakpoints as file", but it doesnt appear, example : 
![image](https://github.com/EugeneSunrise/reWASD/assets/67819275/46e33eea-142f-45ef-966e-6a2ebd56e354)

**Comment by dahcat1** [comment]
yes i have rewasd engine selected, before you ask

**Comment by EugeneSunrise** [comment]
> i did literally everything shown in the video, including changing the folders inside of the xml + adding it to rewasdengine.exe by using "import breakpoints as file", but it doesnt appear, example : 
> 
> ![image](https://github.com/EugeneSunrise/reWASD/assets/67819275/46e33eea-142f-45ef-966e-6a2ebd56e354)
> 
> 

![image](https://github.com/EugeneSunrise/reWASD/assets/56397706/64f1d16b-bed3-4f2d-b27b-4d72d058ae83)

**Comment by dahcat1** [comment]
i have literally done both of those things, i just said that
