### ISSUE TITLE
dnspy issue

### ISSUE THREAD

**Issue by szeress22** [EugeneSunrise/reWASD#56]
![image](https://github.com/EugeneSunrise/reWASD/assets/155153400/1efdf0dd-0eb3-455b-af5a-fd635a4aac1c)

**Comment by ChetFromFalloutNewVegas** [comment]
Can’t read polish

**Comment by szeress22** [comment]
translator
and its hungarian

**Comment by EugeneSunrise** [comment]
Ahahahah are you serious? Go to settings of dnspy and set your language, about issue, contact me in telegram: @sunrjze
