### ISSUE TITLE
is there any better way to automate other than autohotkey?

### ISSUE THREAD

**Issue by gtxg16** [EugeneSunrise/reWASD#58]
like cant dnspy be executed from CLI or something?? autohotkey doesnt always work so u have to do it manually

**Comment by EugeneSunrise** [comment]
> like cant dnspy be executed from CLI or something?? autohotkey doesnt always work so u have to do it manually

Only wait for another developer (Eddy aka reddot, who will also cracking rewasd) will make a patcher
