### ISSUE TITLE
the scan apps and games is not available please need help 

### ISSUE THREAD

**Issue by yurrii22** [EugeneSunrise/reWASD#59]
i cant scan games and apps to set my config on if u played the config without selecting the game it wont work so please i need help

**Comment by EugeneSunrise** [comment]
> i cant scan games and apps to set my config on if u played the config without selecting the game it wont work so please i need help 

I don't understand you, how can I help you?

**Comment by yurrii22** [comment]
> > i cant scan games and apps to set my config on if u played the config without selecting the game it wont work so please i need help
> 
> I don't understand you, how can I help you?

hey sir thanks you for reply can i get your discord so i cant explaine it morefor you?

**Comment by yurrii22** [comment]
im talking about  associated apps option
