### ISSUE TITLE
associated apps option no available

### ISSUE THREAD

**Issue by yurrii22** [EugeneSunrise/reWASD#61]
need help with this bdy  the associated apps option no available and without it the script wont work very well or at all

**Comment by EugeneSunrise** [comment]
Wait 7.0ver

**Comment by yurrii22** [comment]
its gonna take so long right ?

**Comment by EugeneSunrise** [comment]
> its gonna take so long right ?

Yep, holidays bro, im already 🍀

**Comment by yurrii22** [comment]
enjoy bdy thank you anyways
also if theres a way to replace that problem let me know and ahh yeah enjoy ur holidays bdy
