### ISSUE TITLE
Something wrong in debuging. *DnSpy*

### ISSUE THREAD

**Issue by ManuG702** [EugeneSunrise/reWASD#62]
![Captura de pantalla 2023-12-31 174945](https://github.com/EugeneSunrise/reWASD/assets/155334377/66167bfa-b9c4-4303-ae1e-6438c36b90a5)
Translated: An exception occurred when setting the property *System.Windows.ResourceDictionary.Source*.

**Comment by EugeneSunrise** [comment]
> ![Captura de pantalla 2023-12-31 174945](https://github.com/EugeneSunrise/reWASD/assets/155334377/66167bfa-b9c4-4303-ae1e-6438c36b90a5)
> 
> Translated: An exception occurred when setting the property *System.Windows.ResourceDictionary.Source*.

Contact telegram: @sunrjze
