### ISSUE TITLE
when im debugging that said that what is on image

### ISSUE THREAD

**Issue by jxnik11** [EugeneSunrise/reWASD#63]
i have problem after debugging that dont work and i do everything like on video and still cant aply my config
![ss 1](https://github.com/EugeneSunrise/reWASD/assets/155431690/bfac722c-b58b-4b63-9b66-af13f8999077)
![ss 2](https://github.com/EugeneSunrise/reWASD/assets/155431690/921a8725-29fa-406f-96b9-84cb2a756f12)

**Comment by EugeneSunrise** [comment]
> i have problem after debugging that dont work
> 
> ![ss 1](https://github.com/EugeneSunrise/reWASD/assets/155431690/bfac722c-b58b-4b63-9b66-af13f8999077)
> 
> ![ss 2](https://github.com/EugeneSunrise/reWASD/assets/155431690/921a8725-29fa-406f-96b9-84cb2a756f12)
> 
> 
> 
> 

You broke something or installed rewasd incorrectly, go reinstall everything

**Comment by jxnik11** [comment]
ok its working but everytime i quit rewasd its the same shit, eery time i need to reinstall

**Comment by EugeneSunrise** [comment]
> ok its working but everytime i quit rewasd its the same shit, eery time i need to reinstall

It shouldn't be like this, you need to close rewasd correctly, from winows tray, and delete all in assembly editor(dnSpy) except rewasdEngine
