### ISSUE TITLE
Dnspy used to be normal before but today suddenly cant run 

### ISSUE THREAD

**Issue by azeeeezer** [EugeneSunrise/reWASD#64]
![Uploading Screenshot (16).png…]()
it used to be normal until today the DNspy cannot run the REWASD it says 
throw XamLReader ...
and
right below the DNspy there is "Exception : pid ..."

**Comment by azeeeezer** [comment]
![Uploading Screenshot (16).png…]()

**Comment by EugeneSunrise** [comment]
> 
> 
> ![Uploading Screenshot (16).png…]()
> 
> it used to be normal until today the DNspy cannot run the REWASD it says 
> 
> throw XamLReader ...
> 
> and
> 
> right below the DNspy there is "Exception : pid ..."

- [ ] Delete all assemblies in dnSpy(assembly editor) and drop  rewasdEngine there with breakpoints

**Comment by azeeeezer** [comment]
@EugeneSunrise 

nevermind i think my windows defender just erased few data of rewasd so i tried to reinstall rewasd and using dnspy again and its worked.

btw thank you for replying sir

**Comment by bravazeroh** [comment]
This happened to me 3 times, it's because Windows Defender quarantines reWASD.exe. Just allow and restore the program from Windows Defender

**Comment by EugeneSunrise** [comment]
> This happened to me 3 times, it's because Windows Defender quarantines reWASD.exe. Just allow and restore the program from Windows Defender

Whaa thx, I'll use it as an answer

**Comment by EugeneSunrise** [comment]
> This happened to me 3 times, it's because Windows Defender quarantines reWASD.exe. Just allow and restore the program from Windows Defender

Bro, can you help me pls, need to test update for 6.6, contact me in telegram @sunrjze or give me your id
