### ISSUE TITLE
reWASD magic is off

### ISSUE THREAD

**Issue by Juzzly** [EugeneSunrise/reWASD#65]
i cant turn on remap :(((((((((

**Comment by EugeneSunrise** [comment]
> i cant turn on remap :(((((((((

Its very sad 😔

**Comment by Merxlly** [comment]
> i cant turn on remap :(((((((((

me to xd

**Comment by Merxlly** [comment]
![image](https://github.com/EugeneSunrise/reWASD/assets/115192061/54904691-4544-421d-a49b-0fc68fccf99b)
i can turn on

**Comment by Merxlly** [comment]
i cant turn on remap to xd

**Comment by EugeneSunrise** [comment]
I'll reload the second guide tomorrow, and if you guys still have questions, I'll answer them tomorrow.

**Comment by EugeneSunrise** [comment]
Updated readme and reuploaded second guide for noobs, i will close this issue If you don't respond within 24 hours.

**Comment by lukasbrauneruv** [comment]
for some reason everything worked until i clicked the RUN / debug button in dnSpy than i got an exception
https://imgur.com/SOV0due
Any ideas? I disabled Anitvirus i edited the .xml

**Comment by EugeneSunrise** [comment]
> for some reason everything worked until i clicked the RUN / debug button in dnSpy than i got an exception
> 
> https://imgur.com/SOV0due
> 
> Any ideas? I disabled Anitvirus i edited the .xml

Read this issue, i think problem still in defender or your antivirus 

https://github.com/EugeneSunrise/reWASD/issues/64

**Comment by EugeneSunrise** [comment]
> for some reason everything worked until i clicked the RUN / debug button in dnSpy than i got an exception
> 
> https://imgur.com/SOV0due
> 
> Any ideas? I disabled Anitvirus i edited the .xml

Let me know if you fixed problem and how

**Comment by lukasbrauneruv** [comment]
It just started working :D I think i have accidentaly pasted a crack for different version so after reinstalling and doing everything from scratch it fixed itself.  Now i am fighting with the software as it looks a bit different than yours. There is no gamepad and mouse icon also the software might have been updated so it might look different now.

https://imgur.com/ny7zhuv

**Comment by EugeneSunrise** [comment]
> It just started working :D I think i have accidentaly pasted a crack for different version so after reinstalling and doing everything from scratch it fixed itself.  Now i am fighting with the software as it looks a bit different than yours. There is no gamepad and mouse combined icon also the software might have been updated so it might look different now not sure really.
> 
> A short video about the software and different profiles might be good idea.
> 
> https://imgur.com/ny7zhuv

Oh, ok, actually versions are similar, just click on the profile on left side(screenshot)

**Comment by lukasbrauneruv** [comment]
is it possible to have some custom profiles with antirecoil on different weapons for "The Finals" ? Maybe even a guide how to set it up. If we dont wanna spend 50dollars for some random guys profile which we dont even know will be working properly.
I tried some community profiles but its wierd and doesnt have antirecoil for different weapons.

**Comment by lukasbrauneruv** [comment]
> > It just started working :D I think i have accidentaly pasted a crack for different version so after reinstalling and doing everything from scratch it fixed itself.  Now i am fighting with the software as it looks a bit different than yours. There is no gamepad and mouse combined icon also the software might have been updated so it might look different now not sure really.
> > A short video about the software and different profiles might be good idea.
> > https://imgur.com/ny7zhuv
> 
> Oh, ok, actually versions are similar, just click on the profile on left side(screenshot)

i think i accidentaly deleted your profile :D and the community one doesnt have recoil reduction build in atleast for the XP-54

**Comment by lukasbrauneruv** [comment]
https://drive.google.com/file/d/15L47Oa1uzCqDQ7sjSoOhhp4yOp156paC/view?usp=sharing
I got the ZOOM'S 50$ profile for The Finals
you are welcomed!

**Comment by EugeneSunrise** [comment]
> https://drive.google.com/file/d/15L47Oa1uzCqDQ7sjSoOhhp4yOp156paC/view?usp=sharing I got the ZOOM'S 50$ profile for The Finals you are welcomed!



> https://drive.google.com/file/d/15L47Oa1uzCqDQ7sjSoOhhp4yOp156paC/view?usp=sharing I got the ZOOM'S 50$ profile for The Finals you are welcomed!

Actually I dont play games but thanks a lot anyway, a lot of people have asked me about this config, as far as I understand this config contains settings for aim-assist? Can I add a link to the config in the readme?

**Comment by lukasbrauneruv** [comment]
Ye it works with your version and it has aimasssist build in. It has some recoil configs for different weapons but that one i dont use because its wierd and dont help at all. F5 stops/start the script and 5 6 7 8 are different weapon recoil setups.
Also here is a picture of recommended controller settings for maximum aimassist
https://drive.google.com/file/d/1jRJknMF07KPlq5zaeRhYSrqZ7EoV3iwH/view?usp=sharing

**Comment by EugeneSunrise** [comment]
> https://drive.google.com/file/d/1jRJknMF07KPlq5zaeRhYSrqZ7EoV3iwH/view?usp=sharing

Thank you so much❤️
