### ISSUE TITLE
PROBLEM: reWASD, does not see the mouse sensor 6.6 version

### ISSUE THREAD

**Issue by fReMo0** [EugeneSunrise/reWASD#70]

**Comment by fReMo0** [comment]
Eugen, hi, my mouse sensor not detected by reWASD, help pls

**Comment by EugeneSunrise** [comment]
> Eugene, hi, my mouse sensor not detected by reWASD, help pls

Sup bro, pls use "discussion" tab instead of issues and describe your problem normally, also attach a screenshot

**Comment by fReMo0** [comment]
The mouse is determined by REWASD, but when I move the mouse in the game, the key designations become like on MNK, while all the keys on the mouse and keyboard work, and everything is indicated normally in the game. I can't attach a screenshot, sorry

**Comment by yurrii22** [comment]
same problem man thats so bad dude
