### ISSUE TITLE
 rewasd660-7726.exe flags as trojan, not dnSpy

### ISSUE THREAD

**Issue by 2twentyseven** [EugeneSunrise/reWASD#72]
Ran it trough virus total and it came up with at least 30 hits ass a trojan

**Comment by EugeneSunrise** [comment]
> Ran it trough virus total and it came up with at least 30 hits ass a trojan

CHECK README! DONT CREATE DUMB ISSUES! 
INSTALLER FROM https://www.filehorse.com/download-rewasd/80678/
