### ISSUE TITLE
Trojan:Win32/Znyonm

### ISSUE THREAD

**Issue by Genious28** [EugeneSunrise/reWASD#73]
![image](https://github.com/EugeneSunrise/reWASD/assets/97228026/3a2b5c84-9987-4861-a27c-6ac255ca3bc7)

**Comment by EugeneSunrise** [comment]
> ![image](https://github.com/EugeneSunrise/reWASD/assets/97228026/3a2b5c84-9987-4861-a27c-6ac255ca3bc7)
> 
> 

You guys don't seem to be reading README at all, it's already starting to make me angry... And what you want from me???

**Comment by Genious28** [comment]
First of all, Rude.
Secondly.. You mentioned in ReadMe that dnSpy is falsely flagged as Trojan. But here, the Replacement Crack for reWASD.exe is being Flagged as Trojan.
And Finally, everything from Configs and Injections are given absurd amatuer hacker names such as '1337' and then you're being rude when an issue is being pointed out. You're more of a RedFlag than the exe.

> > ![image](https://private-user-images.githubusercontent.com/97228026/295261923-3a2b5c84-9987-4861-a27c-6ac255ca3bc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Mzc3NDIsIm5iZiI6MTcwNDgzNzQ0MiwicGF0aCI6Ii85NzIyODAyNi8yOTUyNjE5MjMtM2EyYjVjODQtOTk4Ny00ODYxLWEyN2MtNmFjMjU1Y2EzYmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDIxNTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYmRhNjRlMDQyZjdlNjM3NDYxMjg1MTllZjMxMjRmYWE4ZmVlMWE3NmQwYzJiZmE0NmU0ZDUzZDI0OTFhZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mxOBqVILb1HlvzgLrlypBo1QaC52BWUFx_rCcQPAZEg)
> 
> You guys don't seem to be reading README at all, it's already starting to make me angry... And what you want from me???

**Comment by EugeneSunrise** [comment]
> First of all, Rude.
> 
> Secondly.. You mentioned in ReadMe that dnSpy is falsely flagged as Trojan. But here, the Replacement Crack for reWASD.exe is being Flagged as Trojan.
> 
> And Finally, everything from Configs and Injections are given absurd amatuer hacker names such as '1337' and then you're being rude when an issue is being pointed out. You're more of a RedFlag than the exe.
> 
> 
> 
> > > ![image](https://private-user-images.githubusercontent.com/97228026/295261923-3a2b5c84-9987-4861-a27c-6ac255ca3bc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Mzc3NDIsIm5iZiI6MTcwNDgzNzQ0MiwicGF0aCI6Ii85NzIyODAyNi8yOTUyNjE5MjMtM2EyYjVjODQtOTk4Ny00ODYxLWEyN2MtNmFjMjU1Y2EzYmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDIxNTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYmRhNjRlMDQyZjdlNjM3NDYxMjg1MTllZjMxMjRmYWE4ZmVlMWE3NmQwYzJiZmE0NmU0ZDUzZDI0OTFhZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mxOBqVILb1HlvzgLrlypBo1QaC52BWUFx_rCcQPAZEg)
> 
> > 
> 
> > You guys don't seem to be reading README at all, it's already starting to make me angry... And what you want from me???
> 
> 
> 
> 

Dear my pakistan friend, ofc I'm rude cuz I'm getting "trojan" issues like every day, and I'm tired of answering the same thing. 
"You mentioned in ReadMe that dnSpy is falsely flagged as Trojan" - You're either blind or stupid my friend, check readme and find "also the other files have no signature, so it can also be a red factor for antivirus". Does it tell you something? If you think the file contains viruses, why are you creating issue at all? What's in your head? Maybe you think that after creating issue, the viruses will disappear? 

I also wrote to use "discussion tab instead of issue" but it looks like you can't read, it will be easier for you to accumulate money and buy a license😁

**Comment by Genious28** [comment]
![image](https://github.com/EugeneSunrise/reWASD/assets/97228026/cc059a78-0edf-45de-8569-89f3d0ff9964)
My dear Russian friend, if you think calling out my place of birth by looking at my profile would make me scared, you're very much wrong. For the rest of the files that do not contain a signature, none of the .dll files in the original setup do anyways. And neither does dnSpy contain a signature yet it is not being flagged as a Trojan. And i wonder why the replacement reWASD.exe is injecting the same Trojan into RegistryKeys.
As for the discussion tab, you're simply a wuss to say that.. Since you clearly just can't stand being called out. As for buying the license, i would if it was one-time only. If you were really a creative CS Student/Graduate, you'd know how awful it feels to have your work plagiarised and/or pirated. Plus, even if you're trying to help needy people, BigTech already infringes enough privacy concerns, we do not need people like you to add to that security concern.


> > First of all, Rude.
> > Secondly.. You mentioned in ReadMe that dnSpy is falsely flagged as Trojan. But here, the Replacement Crack for reWASD.exe is being Flagged as Trojan.
> > And Finally, everything from Configs and Injections are given absurd amatuer hacker names such as '1337' and then you're being rude when an issue is being pointed out. You're more of a RedFlag than the exe.
> > > > ![image](https://private-user-images.githubusercontent.com/97228026/295261923-3a2b5c84-9987-4861-a27c-6ac255ca3bc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Mzc3NDIsIm5iZiI6MTcwNDgzNzQ0MiwicGF0aCI6Ii85NzIyODAyNi8yOTUyNjE5MjMtM2EyYjVjODQtOTk4Ny00ODYxLWEyN2MtNmFjMjU1Y2EzYmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDIxNTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYmRhNjRlMDQyZjdlNjM3NDYxMjg1MTllZjMxMjRmYWE4ZmVlMWE3NmQwYzJiZmE0NmU0ZDUzZDI0OTFhZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mxOBqVILb1HlvzgLrlypBo1QaC52BWUFx_rCcQPAZEg)
> > 
> > 
> > > 
> > 
> > 
> > > You guys don't seem to be reading README at all, it's already starting to make me angry... And what you want from me???
> 
> Dear my pakistan friend, ofc I'm rude cuz I'm getting "trojan" issues like every day, and I'm tired of answering the same thing. "You mentioned in ReadMe that dnSpy is falsely flagged as Trojan" - You're either blind or stupid my friend, check readme and find "also the other files have no signature, so it can also be a red factor for antivirus". Does it tell you something? If you think the file contains viruses, why are you creating issue at all? What's in your head? Maybe you think that after creating issue, the viruses will disappear?
> 
> I also wrote to use "discussion tab instead of issue" but it looks like you can't read, it will be easier for you to accumulate money and buy a license😁

**Comment by EugeneSunrise** [comment]
> My dear Russian friend, if you think calling out my place of birth by looking at my profile would make me scared, you're very much wrong. For the rest of the files that do not contain a signature, none of the .dll files in the original setup do anyways. And neither does dnSpy contain a signature yet it is not being flagged as a Trojan. And i wonder why the replacement reWASD.exe is injecting the same Trojan into RegistryKeys.
> As for the discussion tab, you're simply a wuss to say that.. Since you clearly just can't stand being called out. As for buying the license, i would if it was one-time only. If you were really a creative CS Student/Graduate, you'd know how awful it feels to have your work plagiarised and/or pirated. Plus, even if you're trying to help needy people, BigTech already infringes enough privacy concerns, we do not need people like you to add to that security concern.

> LMAO, ofc you're gonna freak out when I tell you where you were born, especially when a winged rocket flies into your barracks (sorry).

> Since you're so interested in where this redflag came from I'll explain, in order for the crack to work we need to change the code of the library (rewasd.exe and rewasdCommon.dll), after changing the necessary code we save the assembly with metadata and offsets in the heap (and some other things) and after all the manipulations with the assembly we get the redflag from defender. You could check it yourself, but you're a dumb noob and can't do that, instead you need to tell me there are trojans....

> "If you were really a creative CS Student/Graduate, you'd know how awful it feels to have your work plagiarized and/or pirated" - Imma crying😭😭😭😭, if you were a smart student you'd add a protect to your code to make it harder to drop...

> "help needy people" - 😭😭😭😭, I don't give a fuсk, I put almost no effort into this shit.

> Also BigTech don't need little pakistan's kids like you 😘
