### ISSUE TITLE
"Cannot execute "C:\Users\Enzo\AppData\Local\Temp\Rar$EXa19860.34774\reWASD.exe"

### ISSUE THREAD

**Issue by enzolimax1** [EugeneSunrise/reWASD#74]
https://imgur.com/PgEidCo
can you help me?

**Comment by EugeneSunrise** [comment]
> https://imgur.com/PgEidCo
> 
> can you help me?
> 
> 

Firstly use discussions tab instead of issues, honestly I don't know what kind of error it is, maybe it blocks by defender

**Comment by enzolimax1** [comment]
It's not defense, Windows Defender is disabled

**Comment by enzolimax1** [comment]
yes, I use winrar

**Comment by EugeneSunrise** [comment]
> yes, I use winrar
> 
> 

У тебя не получается просто разархивировать файлы?

**Comment by EugeneSunrise** [comment]
> yes, I use winrar
> 
> 

Its error shows when you trying to start rewasd or when trying unzip it?

**Comment by EugeneSunrise** [comment]
> > yes, I use winrar
> > 
> > 
> 
> Its shown an error when you trying to start rewasd or when trying unzip it?

**Comment by enzolimax1** [comment]
> > > yes, I use winrar
> > 
> > 
> > Its shown an error when you trying to start rewasd or when trying unzip it?

When I try to unzip, reWASD.exe does not appear and when it appears it is 1kb

**Comment by EugeneSunrise** [comment]
> > > > yes, I use winrar
> 
> > > 
> 
> > > 
> 
> > > Its shown an error when you trying to start rewasd or when trying unzip it?
> 
> 
> 
> When I try to unzip, reWASD.exe does not appear and when it appears it is 1kb

I still think it's an antivirus, check the logs

**Comment by enzolimax1** [comment]
> I still think it's an antivirus, check the logs

Dude, I have no way of checking this, my anti virus simply doesn't show anything, I got the buggy version of Windows Defender

**Comment by enzolimax1** [comment]
> > I still think it's an antivirus, check the logs
> 
> Dude, I have no way of checking this, my anti virus simply doesn't show anything, I got the buggy version of Windows Defender

I will send you the print

**Comment by enzolimax1** [comment]
> > > I still think it's an antivirus, check the logs
> > 
> > 
> > Dude, I have no way of checking this, my anti virus simply doesn't show anything, I got the buggy version of Windows Defender
> 
> I will send you the print

https://imgur.com/a/KudXAdZ

**Comment by EugeneSunrise** [comment]
> > > > I still think it's an antivirus, check the logs
> 
> > > 
> 
> > > 
> 
> > > Dude, I have no way of checking this, my anti virus simply doesn't show anything, I got the buggy version of Windows Defender
> 
> > 
> 
> > I will send you the print
> 
> 
> 
> https://imgur.com/a/KudXAdZ
> 
> It's in Portuguese, but in short, it's Windows Defender
> 
> 

Its looks very strange xd, you can't even look at the logs :D, ask someone to download this archive and send you the files

**Comment by enzolimax1** [comment]
> > > > > I still think it's an antivirus, check the logs
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Dude, I have no way of checking this, my anti virus simply doesn't show anything, I got the buggy version of Windows Defender
> > 
> > 
> > > 
> > 
> > 
> > > I will send you the print
> > 
> > 
> > https://imgur.com/a/KudXAdZ
> > It's in Portuguese, but in short, it's Windows Defender
> 
> Its looks very strange xd, you can't even look at the logs :D, ask someone to download this archive and send you the files

ok bro
