### ISSUE TITLE
Power Button greyed out!

### ISSUE THREAD

**Issue by DToothedTed** [EugeneSunrise/reWASD#78]
I have reinstalled Rewasd with the crack and it still dose not work I looked online and found a [reddit post](https://www.reddit.com/r/rewasd/comments/18ssn22/power_button_is_greyed_out/) but it did not seem to help me figure out I am using the Finals Script you provided. I used revo uninstaller to uninstall and reinstall the files. Here is a screen shot of the issue. Please help as soon as you can :)
![image](https://github.com/EugeneSunrise/reWASD/assets/121556739/5fcdb4c5-82e9-45a0-af5b-72c269dcedc1)

**Comment by EugeneSunrise** [comment]
> I have reinstalled Rewasd with the crack and it still dose not work I looked online and found a [reddit post](https://www.reddit.com/r/rewasd/comments/18ssn22/power_button_is_greyed_out/) but it did not seem to help me figure out I am using the Finals Script you provided. I used revo uninstaller to uninstall and reinstall the files. Here is a screen shot of the issue. Please help as soon as you can :)
> 
> ![image](https://github.com/EugeneSunrise/reWASD/assets/121556739/5fcdb4c5-82e9-45a0-af5b-72c269dcedc1)
> 
> 
Bro, firstly check readme pls, u can find some interesting info, use discuss tab, i will close this one issue, watch second guide

**Comment by DToothedTed** [comment]
Didn't help, I did everything in the read me with the process ect still dose not work.... Sorry for bothering you :(.

**Comment by EugeneSunrise** [comment]
> Didn't help, I did everything in the read me with the process ect still dose not work.... Sorry for bothering you :(.

Bro, go to discussion tab, one man right now also have that problem

**Comment by DToothedTed** [comment]
Nvm, figured it out I had to close all the things and re-open it sorry for waisted your time :(


(It is grate thx)
