### ISSUE TITLE
Something prevents rewasd background agent from normal functioning

### ISSUE THREAD

**Issue by SmallSideOUO** [EugeneSunrise/reWASD#90]
![Screenshot 2024-01-14 004445](https://github.com/EugeneSunrise/reWASD/assets/33563641/832502f7-ab77-4981-9e86-7b5ce248046a)
It sometimes happened

**Comment by EugeneSunrise** [comment]
> ![Screenshot 2024-01-14 004445](https://github.com/EugeneSunrise/reWASD/assets/33563641/832502f7-ab77-4981-9e86-7b5ce248046a)
> 
> It sometimes happened

Go reinstall all

**Comment by EugeneSunrise** [comment]
Or reboot pc

**Comment by SmallSideOUO** [comment]
ok thanks

**Comment by SmallSideOUO** [comment]
> Or reboot pc

![Screenshot 2024-01-14 005142](https://github.com/EugeneSunrise/reWASD/assets/33563641/9136c6fb-a294-479d-b670-acb87655ad4b)
it working thank you so much
